spring:
  application:
    name: spond-weather
  cache:
    type: caffeine
    cacheNames: locationForecastService
    caffeine:
      spec: recordStats,maximumSize=10000,expireAfterWrite=120m
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

app:
  external:
    met-no:
      base-url: https://api.met.no/weatherapi

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, circuitbreakers
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    root: info
    com.spond.weather: debug