spring:
  application:
    name: spond-weather
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10_000,expireAfterWrite=120m

app:
  external:
    met-no:
      base-url: https://api.met.no/weatherapi

resilience4j:
  circuitbreaker:
    instances:
      met-location-forecast-api:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

logging:
  level:
    root: info
    com.spond.weather: debug